### ISSUE TITLE
Can't delete friendlies

### ISSUE THREAD

**Issue by SilversApprentice** [Johannes2306/Hex-Enhanced-Plus#2]
So, I set up a friendly IP marker(or whatever it's being called) and tested it with no problem. However, when I went to change the name, after I saved it, when I re-connected to the IP, both the new name and the old one showed up. I went back into the Friendly IP tab, and both were now there. I deleted one, and it still popped up, returning to the tab after I went back.

**Comment by jmerle** [comment]
Are you sure you are using v1.1.0? I just tried it right here, and for me adding Friendly IP's, changing it's name or it's IP works perfectly fine.

**Comment by SilversApprentice** [comment]
Sorry for the late reply, I was using v1.1.0, but I think it was actually a problem with my internet, because I tried a couple hours later and it worked
